# -*- coding: utf-8 -*-
"""image processing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ThUlhsiAGe2YSptta4vlgh2M5iSwQR5t
"""

from PIL import Image, ImageFilter
from google.colab import files

uploaded = files.upload()

filename = next(iter(uploaded))  # Gets the first uploaded file

image = Image.open(filename)

smoothed_image = image.filter(ImageFilter.SMOOTH)

smoothed_image.save("smoothed_image.jpg")

smoothed_image.show()

display(smoothed_image)

from PIL import Image
from google.colab import files
from IPython.display import display

uploaded = files.upload()

filename = next(iter(uploaded))
image = Image.open(filename)

angle = 90  # Change this to 180, 270, or any angle you like
rotated_image = image.rotate(angle, expand=True)

output_filename = "rotated_image.jpg"
rotated_image.save(output_filename)
display(rotated_image)

from PIL import Image
from google.colab import files
from IPython.display import display

uploaded = files.upload()

filename = next(iter(uploaded))
image = Image.open(filename)

gray_image = image.convert("L")  # "L" mode is for grayscale

output_filename = "grayscale_image.jpg"
gray_image.save(output_filename)
display(gray_image)

from PIL import Image
from google.colab import files
from IPython.display import display

uploaded = files.upload()

filename = next(iter(uploaded))
image = Image.open(filename)

new_width = 300
new_height = 300
resized_image = image.resize((new_width, new_height))

output_filename = "resized_image.jpg"
resized_image.save(output_filename)
display(resized_image)

!pip install -q rembg onnxruntime

from google.colab import files
uploaded = files.upload()

from rembg import remove
from PIL import Image

filename = next(iter(uploaded))
input_image = Image.open(filename).convert("RGBA")
subject = remove(input_image)

background_color = (0, 128, 255, 255)  # (R, G, B, A) - Blue background
background = Image.new("RGBA", subject.size, background_color)

combined = Image.alpha_composite(background, subject)

output_filename = "changed_background.png"
combined.save(output_filename)

from IPython.display import display
display(combined)

